package net.dave.davesCalamity.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class MandrakeAnimations {
    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(2.952952952952953f).looping()
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.9404404404404403f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.17517517517517517f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9634634634634635f, KeyframeAnimations.degreeVec(-6.79f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.639139139139139f, KeyframeAnimations.degreeVec(-16.24f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.2022022022022023f, KeyframeAnimations.degreeVec(-14.62f, 10f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.615115115115115f, KeyframeAnimations.degreeVec(-10.93f, 4.4f, 0.19f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.9404404404404403f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.23773773773773774f, KeyframeAnimations.degreeVec(12.5f, 0f, -4.95f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6506506506506506f, KeyframeAnimations.degreeVec(22.46f, 0.86f, -4.88f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8258258258258258f, KeyframeAnimations.degreeVec(0.05f, -1.07f, -4.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.2137137137137137f, KeyframeAnimations.degreeVec(0.05f, -1.07f, 0.17f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.564064064064064f, KeyframeAnimations.degreeVec(-7.46f, -1.04f, 0.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.8018018018018018f, KeyframeAnimations.degreeVec(0.05f, -1.07f, 0.17f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.28978978978979f, KeyframeAnimations.degreeVec(-12.46f, -1.01f, 0.39f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.765265265265265f, KeyframeAnimations.degreeVec(0.05f, -1.07f, 0.17f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.12512512512512514f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.43793793793793795f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.950950950950951f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.3138138138138138f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.6641641641641642f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.264764764764765f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.665165165165165f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.8278278278278277f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8258258258258258f, KeyframeAnimations.posVec(0f, -1f, 0.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.364864864864865f, KeyframeAnimations.posVec(0f, -1f, 0.53f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.8778778778778777f, KeyframeAnimations.posVec(0f, -1f, 0.84f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.952952952952953f, KeyframeAnimations.posVec(0f, -1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-32.19f, -1.36f, -3.93f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.33783783783783783f, KeyframeAnimations.degreeVec(-24.71f, -0.84f, -4.07f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6881881881881882f, KeyframeAnimations.degreeVec(-31.23f, 6.22f, -3.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.1511511511511512f, KeyframeAnimations.degreeVec(-30.91f, -2.82f, -3.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.589089089089089f, KeyframeAnimations.degreeVec(-28.72f, -2.29f, -4.06f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.0395395395395397f, KeyframeAnimations.degreeVec(-32.17f, -2.93f, -4.24f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.48998998998999f, KeyframeAnimations.degreeVec(-32.18f, -2.15f, -6.59f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.9404404404404403f, KeyframeAnimations.degreeVec(-32.19f, -1.36f, -3.93f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition START_RUNNING = AnimationDefinition.Builder.withLength(1f)
            .addAnimation("root",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("root",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -2f, 3f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-32.19f, -1.36f, -3.93f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-19.72f, -0.48f, -4.13f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-59.1f, -2.85f, -2.73f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-46.61f, -2.19f, -3.28f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.625f, KeyframeAnimations.degreeVec(-56.6f, -2.73f, -2.85f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-46.61f, -2.19f, -3.28f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-61.6f, -2.97f, -2.6f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_leg",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_leg",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(20.63f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(20.63f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_leg",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_leg",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_arm",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0.05f, -1.07f, 0.17f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0.05f, -1.07f, -62.33f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -57.98f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -72.98f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -65.48f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -70.48f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_arm",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(15f, 0f, 60f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(15f, 0f, 47.5f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(15f, 0f, 57.5f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(15f, 0f, 50f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(15f, 0f, 55f),
    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition RUNNING = AnimationDefinition.Builder.withLength(0.9167666f).looping()
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-59.1f, -2.85f, -2.73f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-46.61f, -2.19f, -3.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-56.6f, -2.73f, -2.85f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-46.61f, -2.19f, -3.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(-61.6f, -2.97f, -2.6f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-46.61f, -2.19f, -3.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(-59.1f, -2.85f, -2.73f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(20.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(20.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -57.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -72.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -65.48f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -70.48f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -65.48f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -57.98f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(15f, 0f, 47.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(15f, 0f, 57.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(15f, 0f, 50f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(15f, 0f, 55f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(15f, 0f, 50f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition STOP_RUNNING = AnimationDefinition.Builder.withLength(0.2916767f)
            .addAnimation("root",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("root",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("hair",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-59.1f, -2.85f, -2.73f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-32.19f, -1.36f, -3.93f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_leg",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_leg",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_leg",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_leg",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("L_arm",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(-0.73f, 1.27f, -57.98f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0.05f, -1.07f, 0.17f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("R_arm",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(15f, 0f, 50f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR))).build();
}